// <auto-generated />
using System;
using MediTrack.Mvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediTrack.Mvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626142124_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MediTrack.Mvc.Models.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuedTo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Issues", (string)null);
                });

            modelBuilder.Entity("MediTrack.Mvc.Models.IssueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicalSupplyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("MedicalSupplyId");

                    b.ToTable("IssueItems", (string)null);
                });

            modelBuilder.Entity("MediTrack.Mvc.Models.MedicalSupply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConcurrencyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplyCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SupplyCategoryId");

                    b.ToTable("MediTrack", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MS-MSK-001",
                            ConcurrencyVersion = 1,
                            CreatedAt = new DateTime(2025, 5, 15, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khau trang y te 3 lop, phu hop cho phong kham",
                            IsDeleted = false,
                            MinStock = 200,
                            Name = "Khau trang y te",
                            Quantity = 500,
                            Supplier = "VinMed",
                            SupplyCategoryId = 1,
                            UnitPrice = 1200m
                        },
                        new
                        {
                            Id = 2,
                            Code = "MS-GLO-002",
                            ConcurrencyVersion = 1,
                            CreatedAt = new DateTime(2025, 5, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gang tay y te khong bot, size M/L",
                            IsDeleted = false,
                            MinStock = 200,
                            Name = "Gang tay cao su",
                            Quantity = 180,
                            Supplier = "VietGlove",
                            SupplyCategoryId = 1,
                            UnitPrice = 3400m
                        },
                        new
                        {
                            Id = 3,
                            Code = "MS-THE-003",
                            ConcurrencyVersion = 1,
                            CreatedAt = new DateTime(2025, 5, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nhiet ke cam tay do nhiet do khong tiep xuc",
                            IsDeleted = false,
                            MinStock = 10,
                            Name = "Nhiet ke hong ngoai",
                            Quantity = 8,
                            Supplier = "Omron Vietnam",
                            SupplyCategoryId = 2,
                            UnitPrice = 320000m
                        },
                        new
                        {
                            Id = 4,
                            Code = "MS-BAN-004",
                            ConcurrencyVersion = 1,
                            CreatedAt = new DateTime(2025, 5, 15, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bong y te tieu khuan, goi 500g",
                            IsDeleted = false,
                            MinStock = 15,
                            Name = "Bong y te",
                            Quantity = 0,
                            Supplier = "Medicare",
                            SupplyCategoryId = 3,
                            UnitPrice = 28000m
                        },
                        new
                        {
                            Id = 5,
                            Code = "MS-SYR-005",
                            ConcurrencyVersion = 1,
                            CreatedAt = new DateTime(2025, 5, 15, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bom tiem 5ml 1 lan su dung",
                            IsDeleted = false,
                            MinStock = 100,
                            Name = "Bom tiem 5ml",
                            Quantity = 220,
                            Supplier = "Kim Tiem Sai Gon",
                            SupplyCategoryId = 3,
                            UnitPrice = 1500m
                        });
                });

            modelBuilder.Entity("MediTrack.Mvc.Models.SupplyCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SupplyCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bao ho"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Thiet bi kiem tra"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tieu hao"
                        });
                });

            modelBuilder.Entity("MediTrack.Mvc.Models.IssueItem", b =>
                {
                    b.HasOne("MediTrack.Mvc.Models.Issue", "Issue")
                        .WithMany("IssueItems")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediTrack.Mvc.Models.MedicalSupply", "MedicalSupply")
                        .WithMany()
                        .HasForeignKey("MedicalSupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("MedicalSupply");
                });

            modelBuilder.Entity("MediTrack.Mvc.Models.MedicalSupply", b =>
                {
                    b.HasOne("MediTrack.Mvc.Models.SupplyCategory", "SupplyCategory")
                        .WithMany("Supplies")
                        .HasForeignKey("SupplyCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupplyCategory");
                });

            modelBuilder.Entity("MediTrack.Mvc.Models.Issue", b =>
                {
                    b.Navigation("IssueItems");
                });

            modelBuilder.Entity("MediTrack.Mvc.Models.SupplyCategory", b =>
                {
                    b.Navigation("Supplies");
                });
#pragma warning restore 612, 618
        }
    }
}
